id: 'ttihp25b'
name: 'Tiny Tapeout IHP 25b'
end_date: '2025-09-01'
project_dir: 'projects'
top_level_macro: 'tt_ihp_wrapper'
powered_netlists: false
no_power_gating: false
pdk: 'ihp-sg13g2'

datasheet_config:

  artwork:
    - {id: TT_POCA_01_A, rotate: 90deg}
    - {id: TT_POCA_01_B, rotate: 90deg}
    - {id: TT_POCA_01_C, rotate: 90deg}
    - {id: TT_POCA_01_D, rotate: -90deg}
    - {id: TT_POCA_01_E, rotate: 90deg}
    - {id: TT_POCA_01_F, rotate: 90deg}
    - {id: TT_POCA_01_G, rotate: 90deg}
    - {id: TT_POCA_01_H, rotate: -90deg}
    - {id: TT_POCA_01_I, rotate: 90deg}

  include:
    - docs/chip_map.typ
    - docs/funding.typ